### ISSUE TITLE
Future me, please look at this. 

### ISSUE THREAD

**Issue by darkhax** [Epoxide-Software/Enchanting-Plus#64]
https://puu.sh/undrC/1f49c0d200.txt

**Comment by darkhax** [comment]
```
at net.darkhax.eplus.item.ItemScroll.enchantScroll(ItemScroll.java:58)
at net.darkhax.eplus.item.ItemScroll.createScroll(ItemScroll.java:47)
at net.darkhax.eplus.handler.ForgeEventHandler.onMobDrops(ForgeEventHandler.java:37)
```
