### ISSUE TITLE
Disconnect and item lost when attempting to repair without enough levels

### ISSUE THREAD

**Issue by dualmoon** [Epoxide-Software/Enchanting-Plus#69]
When trying to repair an enchanted item without having the necessary levels to complete the repair, the server disconnects and the item is lost entirely.

```
[19:44:28] [Netty Epoll Server IO #10/ERROR] [FML]: There was a critical exception handling a packet on channel EnchantingPlus
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at net.darkhax.eplus.inventory.ContainerAdvancedTable.canPurchase(ContainerAdvancedTable.java:389) ~[ContainerAdvancedTable.class:?]
        at net.darkhax.eplus.inventory.ContainerAdvancedTable.repair(ContainerAdvancedTable.java:147) ~[ContainerAdvancedTable.class:?]
        at net.darkhax.eplus.common.network.packet.PacketRepairItem$PacketHandler.onMessage(PacketRepairItem.java:52) ~[PacketRepairItem$PacketHandler.class:?]
        at net.darkhax.eplus.common.network.packet.PacketRepairItem$PacketHandler.onMessage(PacketRepairItem.java:43) ~[PacketRepairItem$PacketHandler.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:56) ~[SimpleChannelHandlerWrapper.class:?]
```

**Comment by darkhax** [comment]
Newer versions of this mod store the item in the tile nbt like a chest. This will prevent this issue from happening. Older versions are not supported so they wont be getting this update.
